### ISSUE TITLE
Clarification about when you play Conditions

### ISSUE THREAD

**Issue by JayLoomis** [astralfrontier/flip-a-card#10]
It's clear from what's already written that you (a player) play a condition on yourself in order to get a hit. You also have the option to subsequently flip it to the aggravated side to get another hit.

There is no mention of a condition ever being imposed on you from external sources.

Here are two that come to my mind as I review:

1.  The facilitator presents a situation in the fiction that, if not addressed, will logically lead to a
     condition.

    Example: You're distracted trying to grab the MacGuffin that's being taken away by angry birds.
    The facilitator narrates that a bandit appears through the foliage to lash out at you with her
    sword. You choose to stick with the MacGuffin, so the fiction demands that you get the "Stabbed
    Up" condition.

2.  The natural course of the fiction demands that you've got a condition.

    Example: You're having a laser sword fight on a volcanic planet. Your enemy is relentless, but the
    heat of the place is overwhelming. If you don't find a way to get out of there, you're going to get
    burnt.

Some of this discussion begs questions about how the flow of play works. Do you have a limited action economy that dictates you can only do one thing at a time? Or can you narrate your way out of either/or situations with enough hits?

**Comment by astralfrontier** [comment]
I left some examples of how conditions work:

https://astralfrontier.github.io/flip-a-card/cards/condition-cards-condition-examples

Does this address points 1 and 2?

There's no action economy _per se_, just a card economy. You can narrate your way out of situations with enough hits, but (unless you're using dice) that leaves you with a finite number of cards to use. After that, you cede control of your narration to whoever challenged you. I'll talk more about this when I rewrite the Challenges rule card.
