### ISSUE TITLE
Break long lines in YAML files?

### ISSUE THREAD

**Issue by JayLoomis** [astralfrontier/flip-a-card#30]
It would be a great boon to editing the cards if the text in the YAML files was broken at a consistent, reasonable line length (80 or 120 chars, e.g.).

I don't know enough about the parsing tools you're using to know if there's a technical reason not to do so, but it would be a help if not.

**Comment by astralfrontier** [comment]
It's standard YAML. Right now the format I've chosen makes every line its own paragraph. You can see different standards here:

https://yaml-multiline.info/

**Comment by astralfrontier** [comment]
Examples:

```yaml
example: >
  This is a paragraph
  with long lines

  This is another paragraph
key: value
```

parses as:

```json
{
  "example": "This is a paragraph with long lines\nThis is another paragraph\n", 
  "key": "value"
}
```

That's equivalent to how I'm doing it today:

```yaml
desc: |-
  This is a single-line sentence.
  This is another paragraph.
key: value
```

**Comment by astralfrontier** [comment]
If we can get the two pending PRs done, I'll convert the rest of the cards.

**Comment by JayLoomis** [comment]
Yes, I looked up the YAML formatting options, but then decided I'd ask rather than trying to piece together the requirements and idiosyncrasies of your tools.

GitHub is, it seems, designed with the assumption that columns in source files will be limited (especially evident in PR reviewing).
