### ISSUE TITLE
You can roll a die, but do you?

### ISSUE THREAD

**Issue by JayLoomis** [astralfrontier/flip-a-card#6]
How does simple dice interact with the baseline rule? Do you have the option to roll a die instead of flipping a card? Do you have to roll a die when you flip a card? Does the presence or absence of a relevant card affect the die roll at all--that is, if I have a card that would apply, do I get a bonus (or a penalty if I don't)?

https://github.com/astralfrontier/flip-a-card/blob/bdb4531aff0b551a791672c5444c592cf6dfb920/card-data/00-core.yaml#L55

**Comment by astralfrontier** [comment]
This is mostly a demo card to show how dice would be incorporated into a game. I can move it to a separate category to make that clear. I'll also update the wording.

**Comment by JayLoomis** [comment]
New wording is clarifying.
