### ISSUE TITLE
Origins feel anomalous in the character cards

### ISSUE THREAD

**Issue by JayLoomis** [astralfrontier/flip-a-card#7]
Unlike the role cards, which feel very much like, you're an opportunist which makes you effective and cool when you do these (front side) things, but you often get into trouble because of these (flip side) things, origins don't feel like the sides are clearly themed. At first I thought the front side was positive stereotypes, and the flip side was negative stereotypes, but I'm not sure that bears out. If it is meant to be that, I should do another pass and give suggestions.

Then, I'm really conflicted by the subverting the stereotype prompt, and its placement on the flip side. If I'm reading your intention right, this is a way to reward you for asserting a thing about your character that transcends the expectations of their background. If so, I think that's awesome! But putting it on the flip side dilutes the distinction between the sides. I suggest that the subvert prompt go on both sides--it's always an option. One cool addition might be that when you choose to subvert, you add a prompt appropriate to the side you're on. So on the flip side, I could add troublesome individual characteristics, and on the front side mostly positive ones. Just spit-balling there.

https://github.com/astralfrontier/flip-a-card/blob/bdb4531aff0b551a791672c5444c592cf6dfb920/card-data/01-character-origin.yaml#L20

**Comment by astralfrontier** [comment]
Will be replaced with Upbringing cards.
