### ISSUE TITLE
More description needed for conditions

### ISSUE THREAD

**Issue by JayLoomis** [astralfrontier/flip-a-card#8]
This card should have some instruction about what having a condition means. I think what it means is that the card is an assertion in the fiction. If it applies to a situation it might create a challenge or make something impossible. But that's just me guessing. I don't want to have to guess.

https://github.com/astralfrontier/flip-a-card/blob/bdb4531aff0b551a791672c5444c592cf6dfb920/card-data/02-conditions.yaml#L11

**Comment by astralfrontier** [comment]
https://astralfrontier.github.io/flip-a-card/cards/condition-cards-condition-examples

This should answer the questions of "what does it mean", "is it true in the fiction", and "does it force a challenge".
