### ISSUE TITLE
Not sure how challenge cards work thematically

### ISSUE THREAD

**Issue by JayLoomis** [astralfrontier/flip-a-card#9]
This example of a challenge card doesn't conform to any of the existing patterns for cards. And it's not clear to me how they're supposed to work.

One possibility would be that the card is introduced with the face value up. The bandit is sneaky and armed, etc. Then, if you score a hit on a bandit it could flip and show weaknesses.

Another possibility would be that challenges have modes. That's what seems to be going on with the bandit right now. The front side has non-aggressive bandit prompts, and the back has aggressive mode prompts. I'm not at all sure how these flip or interact with other stuff though.

https://github.com/astralfrontier/flip-a-card/blob/bdb4531aff0b551a791672c5444c592cf6dfb920/card-data/03-challenges-encounters.yaml#L5-L19

**Comment by astralfrontier** [comment]
The current model for these cards is:

* the front side is "GM moves", or things that pose challenges
* the flip side is things that let you avoid or meet challenges

**Comment by astralfrontier** [comment]
Marking closed as #26 will supercede it
